TILE_SIZE = 32

SCREEN_TILE_WIDTH = 30
SCREEN_WIDTH = TILE_SIZE * SCREEN_TILE_WIDTH

SCREEN_TILE_HEIGHT = 20
SCREEN_HEIGHT = TILE_SIZE * SCREEN_TILE_HEIGHT

TOP_BAR_TILE_HEIGHT = 2
TOP_BAR_HEIGHT = TILE_SIZE * TOP_BAR_TILE_HEIGHT

MENU_TILE_HEIGHT = 5
MENU_HEIGHT = TILE_SIZE * MENU_TILE_HEIGHT

MAP_TILE_HEIGHT = SCREEN_TILE_HEIGHT - TOP_BAR_TILE_HEIGHT - MENU_TILE_HEIGHT
MAP_HEIGHT = TILE_SIZE * MAP_TILE_HEIGHT

MAP_TILE_WIDTH = SCREEN_TILE_WIDTH
MAP_WIDTH = TILE_SIZE * MAP_TILE_WIDTH

