TILE_SIZE = 32

SCREEN_WIDTH_IN_TILES = 30
SCREEN_WIDTH = TILE_SIZE * SCREEN_WIDTH_IN_TILES

SCREEN_HEIGHT_IN_TILES = 20
SCREEN_HEIGHT = TILE_SIZE * SCREEN_HEIGHT_IN_TILES

TOP_BAR_HEIGHT_IN_TILES = 2
TOP_BAR_HEIGHT = TILE_SIZE * TOP_BAR_HEIGHT_IN_TILES

MENU_HEIGHT_IN_TILES = 5
MENU_HEIGHT = TILE_SIZE * MENU_HEIGHT_IN_TILES

MAP_HEIGHT_IN_TILES = SCREEN_WIDTH_IN_TILES - TOP_BAR_HEIGHT_IN_TILES - MENU_HEIGHT_IN_TILES
MAP_HEIGHT = TILE_SIZE * MAP_HEIGHT_IN_TILES


